### ISSUE TITLE
IllegalArgumentException occurred while creating a query in EntityManager during change filtering condition

### ISSUE THREAD

**Issue by maistrenkoIulia** [cuba-platform/cuba#3113]
see https://www.cuba-platform.com/discuss/t/error-when-switching-filter-operator/12319/5
### Environment
CUBA Platform version: 7.1.8
CUBA Studio plugin version: 15.0.SNAPSHOT2679-202
IntelliJ version: IntelliJ IDEA 2020.2.4 (Community Edition)

### Description of the bug or enhancement

- Minimal reproducible example
[DateTimeSample.zip](https://github.com/cuba-platform/cuba/files/5659416/DateTimeSample.zip)
- Launch app
- Open WorkOrder browser
- Select By District
- Select some entities - fill the list
- Change the operator from "Not in" to "In"
- Perform filtering Search

AR:
```
com.haulmont.cuba.core.global.RemoteException:
---
java.lang.IllegalArgumentException: An exception occurred while creating a query in EntityManager: 
Exception Description: Problem compiling [select e from datetimesample_WorkOrder e where districtYGgey.district.id in :component_filter_district66743 order by e.start]. 
[47, 72] The state field path 'districtYGgey.district.id' cannot be resolved to a valid type.
[47, 60] The identification variable 'districtYGgey' is not defined in the FROM clause.
---
org.eclipse.persistence.exceptions.JPQLException: 
Exception Description: Problem compiling [select e from datetimesample_WorkOrder e where districtYGgey.district.id in :component_filter_district66743 order by e.start]. 
[47, 72] The state field path 'districtYGgey.district.id' cannot be resolved to a valid type.
[47, 60] The identification variable 'districtYGgey' is not defined in the FROM clause.
	at com.haulmont.cuba.core.sys.ServiceInterceptor.aroundInvoke(ServiceInterceptor.java:124)
	at sun.reflect.GeneratedMethodAccessor119.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy200.loadList(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor149.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.haulmont.cuba.core.sys.remoting.LocalServiceInvokerImpl.invoke(LocalServiceInvokerImpl.java:94)
	at com.haulmont.cuba.web.sys.remoting.LocalServiceProxy$LocalServiceInvocationHandler.invoke(LocalServiceProxy.java:154)
	at com.sun.proxy.$Proxy36.loadList(Unknown Source)
	at com.haulmont.cuba.client.sys.DataManagerClientImpl.loadList(DataManagerClientImpl.java:57)
	at com.haulmont.cuba.gui.data.impl.GenericDataSupplier.loadList(GenericDataSupplier.java:117)
	at com.haulmont.cuba.gui.data.impl.CollectionDatasourceImpl.loadData(CollectionDatasourceImpl.java:624)
	at com.haulmont.cuba.gui.data.impl.CollectionDatasourceImpl.refresh(CollectionDatasourceImpl.java:165)
	at com.haulmont.cuba.gui.data.impl.CollectionDatasourceImpl.refreshIfNotSuspended(CollectionDatasourceImpl.java:116)
	at com.haulmont.cuba.gui.components.filter.FilterDelegateImpl$DatasourceAdapter.refreshIfNotSuspended(FilterDelegateImpl.java:3600)
	at com.haulmont.cuba.gui.components.filter.FilterDelegateImpl.refreshDatasource(FilterDelegateImpl.java:1880)
	at com.haulmont.cuba.gui.components.filter.FilterDelegateImpl.apply(FilterDelegateImpl.java:1705)
	at com.haulmont.cuba.gui.components.filter.FilterDelegateImpl.apply(FilterDelegateImpl.java:1726)
	at com.haulmont.cuba.gui.components.filter.FilterDelegateImpl.lambda$createControlsLayoutForGeneric$1(FilterDelegateImpl.java:316)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.web.gui.components.WebAbstractComponent.publish(WebAbstractComponent.java:92)
	at com.haulmont.cuba.web.gui.components.WebButton.buttonClicked(WebButton.java:67)
	at com.haulmont.cuba.web.widgets.CubaButton.fireClick(CubaButton.java:76)
	at com.vaadin.ui.Button$1.click(Button.java:57)
```
### QA
Filters created before 7.1.8 version should be recreated, like the filter in the case described above. In 7.1.8 there is a backported fix: https://github.com/cuba-platform/cuba/pull/2930

Use 7.1 for testing:
1. Check the case above for the new created filters.
2. Please check https://github.com/cuba-platform/cuba/issues/3113#issuecomment-889169205 that Alex Budarov reported.

**Comment by knstvk** [comment]
@maistrenkoIulia Is it reproduced on 7.2?

**Comment by maistrenkoIulia** [comment]
@knstvk, yes
reproduced on 
CUBA Platform version: 7.2.10
CUBA Studio plugin version: 15.0.SNAPSHOT2687-202
IntelliJ version: IntelliJ IDEA 2020.2.4 (Community Edition)

**Comment by glebfox** [comment]
This issue has been fixed in https://github.com/cuba-platform/cuba/issues/2866. Unfortunately, it isn't mentioned that all saved filters must be recreated in order to have the correct definition, because we can't update saved `Filter` entities during the platform version update.

In order to test this, check the Filter XML value in DB:

The buggy one:
```
<filter>
  <and>
    <c name="district" class="com.company.datetimesample.entity.District" inExpr="true" operatorType="NOT_IN" width="1" type="PROPERTY"><![CDATA[((districtYGgey.id not in :component$filter.district66743) or (districtYGgey.id is null)) ]]>
      <param name="component$filter.district66743" javaClass="com.company.datetimesample.entity.District">NULL</param>
      <join><![CDATA[left join districtgSBzY.district districtYGgey]]></join>
    </c>
  </and>
</filter>
```

Fixed one
```
  <and>
    <c name="district" class="com.company.datetimesample.entity.District" inExpr="true" operatorType="NOT_IN" width="1" type="PROPERTY" entityAlias="e"><![CDATA[((districtasLWK.id not in :component$filter.district69937) or (districtasLWK.id is null)) ]]>
      <param name="component$filter.district69937" javaClass="com.company.datetimesample.entity.District">NULL</param>
      <join><![CDATA[left join e.district districtasLWK]]></join>
    </c>
  </and>
</filter>
```

As you can see, the new `entityAlias="e"` attribute is added and it is used in the `<join>` section.

**Comment by alexbudarov** [comment]
The bug isn't fixed. It isn't caused by old filters saved to the database by the previous CUBA version. Can be reproduced on new database.
Steps to reproduce:
- open sample project
- re-create the database
- launch application
- Create District "test"
- open WorkOrder browser
- Create filter "District not in". Save filter.
- reopen WorkOrder browser.
- select saved filter from the drop-down field.
- Change condition to "In".
- Add previously created "test" District to the lookup field.
- Press Search.
- Exception occurs:

```
JPQLException: 
Exception Description: Problem compiling [select e from datetimesample_WorkOrder e where districtDQGdX.district.id in :component_filter_district48623]. 
[47, 72] The state field path 'districtDQGdX.district.id' cannot be resolved to a valid type.
[47, 60] The identification variable 'districtDQGdX' is not defined in the FROM clause.
```

**Comment by maistrenkoIulia** [comment]
verified
